/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./sections/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f9f9f9",
        "on-secondary": "#ffffff",
        "on-surface": "#1a1c1c",
        "error": "#ba1a1a",
        "on-background": "#1a1c1c",
        "on-secondary-fixed": "#1b1b1b",
        "surface": "#f9f9f9",
        "outline": "#7c775f",
        "primary-fixed": "#fde400",
        "on-primary-container": "#726600",
        "surface-container": "#eeeeee",
        "secondary": "#5e5e5e",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e2e2",
        "surface-container-low": "#f3f3f3",
        "secondary-fixed-dim": "#c6c6c6",
        "primary-container": "#ffe600",
        "on-tertiary-fixed-variant": "#474747",
        "on-primary-fixed-variant": "#504700",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-container": "#e6e4e3",
        "on-primary": "#ffffff",
        "outline-variant": "#cdc7aa",
        "on-primary-fixed": "#201c00",
        "surface-dim": "#dadada",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f3131",
        "on-tertiary-container": "#666565",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-surface-variant": "#4b4731",
        "surface-container-high": "#e8e8e8",
        "primary": "#6a5f00",
        "inverse-primary": "#dec800",
        "surface-bright": "#f9f9f9",
        "primary-fixed-dim": "#dec800",
        "on-secondary-container": "#646464",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary": "#5f5e5e",
        "surface-container-highest": "#e2e2e2",
        "on-error": "#ffffff",
        "secondary-container": "#e2e2e2",
        "on-tertiary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474747",
        "secondary-fixed": "#e2e2e2",
        "tertiary-fixed": "#e4e2e1",
        "surface-tint": "#6a5f00"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0px", 
        "lg": "0px", 
        "xl": "0px", 
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
